package Utils;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.Date;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;

public class PdfReport {
    private static final Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18, Font.BOLD);
    private static final Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.NORMAL, BaseColor.RED);
    private static final Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16, Font.BOLD);
    private static final Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD);

    public void addTitlePage(Document document) throws DocumentException {
        Paragraph preface = new Paragraph();
        // We add one empty line
        addEmptyLine(preface, 1);
        // Lets write a big header
        preface.add(new Paragraph("Drive X port", catFont));

        addEmptyLine(preface, 1);
        // Will create: Report generated by: _name, _date
        preface.add(new Paragraph("Reporte generado por: " + System.getProperty("user.name") + ", " + new Date()));
        addEmptyLine(preface, 1);
        preface.add(new Paragraph("Reporte de inventario ", smallBold));
        addEmptyLine(preface, 2);
        preface.add(new Paragraph("El reporte contiene datos del inventario hasta le momento de creacion de este documento.", redFont));
        document.add(preface);
        // Start a new page
        document.newPage();
    }


    public void createContentTable(Document document, ResultSet content) throws DocumentException, SQLException {
        Paragraph preface = new Paragraph();
        float cantidad_total = 0;
        int unidadades_totales = 0;
        PdfPTable table = new PdfPTable(5);

        PdfPCell c1 = new PdfPCell(new Phrase("Codigo producto"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Nombre Producto"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Existencia"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        table.setHeaderRows(1);

        c1 = new PdfPCell(new Phrase("Precio Unitario"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        table.setHeaderRows(1);

        c1 = new PdfPCell(new Phrase("Modificado"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        table.setHeaderRows(1);

        while (content.next()){
            String codigo_producto = content.getString(1);
            String nombre_producto = content.getString(2);
            int cantidad_producto = Integer.parseInt(content.getString(3));
            float precio = Float.parseFloat(content.getString(4));
            String date = content.getString(5);
            unidadades_totales += cantidad_producto;
            cantidad_total += (cantidad_producto * precio);
            table.addCell(codigo_producto);
            table.addCell(nombre_producto);
            table.addCell(String.valueOf(cantidad_producto));
            table.addCell(String.valueOf(precio));
            table.addCell(date);
        }

        document.add(table);

        NumberFormat formatter = NumberFormat.getCurrencyInstance();
        String moneyString = formatter.format(cantidad_total);
        addEmptyLine(preface, 5);
        preface.add(new Paragraph("Total unidades " + unidadades_totales + "\nGran total: "+ moneyString));
        document.add(preface);
        // Start a new page
        document.newPage();
    }

    private static void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    }
}
