/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Utils.GenerateInvoice;
import Utils.GenerateNamePath;
import Utils.Queries;
import Utils.Validations;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Jaime Tuyuc
 */
public class InvoiceForm extends javax.swing.JFrame  {

    //* Name to save files
    GenerateNamePath generateNamePath = new GenerateNamePath();

    //* Generate Invoide
    GenerateInvoice invoice = new GenerateInvoice();

    Queries querydb = new Queries();

    Validations validations = new Validations();

    static String product_id = "", product_from_db_name = "", product_from_db_price = "", amount_from_db = "";
    static int user_id = 0, amount_to_extract = 0, amount_to_sell = 0;

    float total_sell_price_with_no_iva = 0f, iva_price = 0f, price_with_iva = 0f;

    final float IVA = 0.12f;

    String desktopPath = System.getProperty("user.home") + File.separator +"Desktop";


    public InvoiceForm(String id_product_invoice, int user_seller, int amount) throws SQLException {
        product_id = id_product_invoice;
        user_id = user_seller;
        amount_to_extract = amount;
        getAllDbRequiredInfo(product_id, user_id, amount_to_extract);
        initComponents();
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setVisible(false);
    }

    private void getAllDbRequiredInfo(String product_id, int user_seller, int amount) throws SQLException {
        ResultSet data_from_db = querydb.getSingleProductDb( product_id, user_seller);
        while (data_from_db.next()){
            product_from_db_name = data_from_db.getString(2);
            amount_from_db = data_from_db.getString(3);
            product_from_db_price = data_from_db.getString(4);
        }

        amount_to_sell = Integer.parseInt(amount_from_db) - amount;
        total_sell_price_with_no_iva = amount_to_sell * Float.parseFloat(product_from_db_price);
        iva_price = (IVA * total_sell_price_with_no_iva);
        price_with_iva = iva_price + total_sell_price_with_no_iva;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        customer_number = new javax.swing.JTextField();
        customer_email = new javax.swing.JTextField();
        customer_full_name = new javax.swing.JTextField();
        customer_address = new javax.swing.JTextField();
        customer_postal_number = new javax.swing.JTextField();
        create_invoice = new javax.swing.JButton();
        cancel_invoice = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Informacion de Cliente");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Telefono");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Nombre Cliente");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Correo Electronico");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Codigo Postal");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Direccion de envio");

        customer_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_emailActionPerformed(evt);
            }
        });

        customer_full_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_full_nameActionPerformed(evt);
            }
        });

        customer_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_addressActionPerformed(evt);
            }
        });

        customer_postal_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_postal_numberActionPerformed(evt);
            }
        });

        create_invoice.setText("CONTINUAR");
        create_invoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    create_invoiceActionPerformed(evt);
                } catch (SQLException | FileNotFoundException | DocumentException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        cancel_invoice.setText("CANCELAR");
        cancel_invoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_invoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancel_invoice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(create_invoice))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(customer_postal_number, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(customer_address, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(customer_email, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(customer_number, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(customer_full_name, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(customer_full_name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(customer_number, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(customer_email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(jLabel6))
                    .addComponent(customer_address, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(customer_postal_number, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create_invoice)
                    .addComponent(cancel_invoice))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customer_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_emailActionPerformed

    private void customer_full_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_full_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_full_nameActionPerformed

    private void customer_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_addressActionPerformed

    private void customer_postal_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_postal_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_postal_numberActionPerformed

    private void create_invoiceActionPerformed(java.awt.event.ActionEvent evt) throws SQLException, DocumentException, FileNotFoundException {//GEN-FIRST:event_create_invoiceActionPerformed
        int isUpdated = 0;
        String invoiceName = generateNamePath.generatePathToSaveInfo("Factura", desktopPath);
        Document document = invoice.generateSingleInvoice(invoiceName);

        if(customer_full_name.getText().isEmpty() || customer_email.getText().isEmpty() || customer_number.getText().isEmpty() || customer_address.getText().isEmpty() || customer_postal_number.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Los campos no pueden estar vacios para continuar");
            return;
        }else if( !validations.validateEmailAddress(customer_email.getText())){
            JOptionPane.showMessageDialog(null, "Por favor ingresa un correo valido");
            return;
        }else {
            isUpdated = querydb.updateRecordOnDb(amount_to_extract, user_id, product_id);
        }
        //? Validar que si se haya actualizado para crear la factura
        if(isUpdated == 1){
            //? Llenar los datos
            invoice.createHeader(document);
            invoice.billingCustomerInfo(document, customer_full_name.getText(), customer_number.getText(), customer_email.getText(), customer_address.getText(), customer_postal_number.getText());
            invoice.productInfoTable(document, product_from_db_name, amount_to_sell, total_sell_price_with_no_iva, IVA, iva_price);
            invoice.tableTotalProduct(document, price_with_iva);
            invoice.footerContent(document);
            document.newPage();
            document.close();
            JOptionPane.showMessageDialog(null, "Proceso realizado correctamente : )");
//            this.setVisible(false);
        }else {
            JOptionPane.showMessageDialog(null, "Oops, algo no salio como lo esperabamos :(");
        }
        this.dispose();
    }//GEN-LAST:event_create_invo iceActionPerformed

    private void cancel_invoiceActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cancel_invoiceActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancel_invoiceActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InvoiceForm(product_id, user_id, amount_to_extract).setVisible(true);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_invoice;
    private javax.swing.JButton create_invoice;
    private javax.swing.JTextField customer_address;
    private javax.swing.JTextField customer_email;
    private javax.swing.JTextField customer_full_name;
    private javax.swing.JTextField customer_number;
    private javax.swing.JTextField customer_postal_number;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
